binop_separator = "Back"
comment_width = 120
doc_comment_code_block_width = 120
format_code_in_doc_comments = true
format_strings = true
fn_params_layout = "Vertical"
imports_granularity = "Crate"
max_width = 120
merge_derives = true
reorder_imports = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true